import { Router } from 'express';
import { uploadDocument, getDocuments, deleteDocument, searchDocuments } from '../controllers/document.controller.js';
import { authenticate } from '../middleware/auth.js';
import { upload } from '../middleware/upload.js';
const router = Router();
router.use(authenticate);
router.get('/', getDocuments);
router.post('/upload', upload.single('file'), uploadDocument);
router.delete('/:id', deleteDocument);
router.post('/search', searchDocuments);
export default router;
